### ISSUE TITLE
load_test, lauch_testsに関して、不正な値が入ってきたときに適切なエラーを返すかどうかチェックするテストを作成する。

### ISSUE THREAD

**Issue by kohkubo** [fujimoto-code/libunit2#9]

**Comment by kohkubo** [comment]
こちらに関しては関数の返り値を想定の値を比較するテストを作成してください。

main関数を用意し、期待する結果が返って来ているかをチェックする関数です。

**Comment by fujimoto-code** [comment]
具体的にlaunch_testの返り値を見ればいいですか？

**Comment by kohkubo** [comment]
確かに、元の要件が曖昧だとテスト書けないですね。

load_test, launch_testsと、NULLが来たら、
メッセージ(load_test : Invalid argument. )と共にexit(1)で終了ステータスをエラーで終了するようにしましょうか。

このテスト方法が良いのか、自分でも自信がないのですが、
forkさせて、print_statusと同じロジックを使ってエラー終了しているか、取得して、予想される結果(終了ステータスがエラー)だったら、OKを出力する。とかどうでしょうか。

複雑すぎますか？

負荷テストだと、とりあえずクラッシュしないか見るだけで良かったのですが、unit testだと複雑になりますね。

アイディアください！
